### ISSUE TITLE
Launching from Store crashes HP, but not launching from Library

### ISSUE THREAD

**Issue by awantoch** [HyperPlay-Gaming/hyperplay-desktop-client#403]
### Describe the bug

When launching a game from the Store page, the client crashes.

However, you can launch the same game from the Library page without fail.

### Add logs

```
(17:08:15) INFO:    [Legendary]:        Refreshing library...
(17:08:15) INFO:    [Backend]:          Loading MetaMask extension
(17:08:15) INFO:    [Connection]:       Connectivity: check-online
(17:08:15) INFO:    [Connection]:       Pinging external endpoints
(17:08:15) INFO:    [Backend]:          Creating abort controller for legendary-version
(17:08:15) INFO:    [Legendary]:        Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:08:15) INFO:    [Legendary]:        Legendary location: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary
(17:08:15) INFO:    [Gog]:              GOGDL location: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:08:15) INFO:    [Gog]:              GOGDL location: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:08:15) WARNING: [Backend]:          Protocol already registered.
(17:08:15) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(17:08:15) INFO:    [Backend]:          MetaMask extension loaded
(17:08:16) INFO:    [Connection]:       Connectivity: online
(17:08:16) INFO:    [Backend]:          User Not Found, removing it from Store
(17:08:16) INFO:    [Backend]:          Auto Updater found version: 0.3.0 released on 2023-06-28T07:39:39.575Z with name 0.3.0
(17:08:16) INFO:    [Backend]:          Deleting abort controller for legendary-version
(17:08:16) INFO:    [Backend]:          Creating abort controller for gogdl-version
(17:08:16) INFO:    [Gog]:              Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:08:17) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(17:08:18) INFO:    [WineDownloader]:   Updating wine versions info
(17:08:18) INFO:    [WineDownloader]:   Fetching upstream information...
(17:08:18) INFO:    [Backend]:          Frontend Ready
(17:08:18) INFO:    [Backend]:          Loading Screen Ready
(17:08:18) INFO:    [Frontend]:         Refreshing Library
(17:08:19) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:08:19) INFO:    [Gog]:              Found 0 game(s) to update
(17:08:19) INFO:    [WineDownloader]:   wine versions updated
(17:08:19) ERROR:   [Backend]:          Could not find default wine version
(17:08:23) INFO:    [Backend]:          Starting the Download Queue
(17:08:31) INFO:    [ProtocolHandler]:  received 'hyperplay://launch/hyperplay/63f69d82069b92b74c8c36e9'
(17:08:31) INFO:    [ProtocolHandler]:  "Altiros" not installed.
(17:08:34) INFO:    [HyperPlay]:        Getting install info for Altiros
(17:08:39) INFO:    [HyperPlay]:        Getting install info for Altiros
(17:08:39) INFO:    [DownloadManager]:  Altiros  was added to the download queue.
(17:08:39) INFO:    [HyperPlay]:        Installing Altiros to C:\Users\Shadow\Games\HyperPlay...
(17:08:39) INFO:    [HyperPlay]:        Downloading zip file to C:\Users\Shadow\AppData\Roaming\hyperplay\.temp\63f69d82069b92b74c8c36e9\hyperplay_442.zip
(17:08:39) INFO:    [HyperPlay]:        Downloading from https://gateway.valist.io/ipfs/bafybeighwdyicwuobywg35wspky7tzmlorokccxll7nxzvy3mkreib7534/windows_amd64/hyperplay_442.zip
(17:08:39) INFO:    [Backend]:          Creating abort controller for 63f69d82069b92b74c8c36e9
(17:08:39) INFO:    [Backend]:          Preventing machine to sleep
(17:08:40) INFO:    [HyperPlay]:        Downloaded: 25.72 MB / 591.24 MB  @32.93 MB/s (4.35%)
(17:08:41) INFO:    [HyperPlay]:        Downloaded: 79.56 MB / 591.24 MB  @46.36 MB/s (13.46%)
(17:08:43) INFO:    [HyperPlay]:        Downloaded: 141.88 MB / 591.24 MB  @35.58 MB/s (24.00%)
(17:08:44) INFO:    [HyperPlay]:        Downloaded: 169.51 MB / 591.24 MB  @17.51 MB/s (28.67%)
(17:08:45) INFO:    [HyperPlay]:        Downloaded: 211.28 MB / 591.24 MB  @32.21 MB/s (35.73%)
(17:08:46) INFO:    [HyperPlay]:        Downloaded: 256.78 MB / 591.24 MB  @28.07 MB/s (43.43%)
(17:08:48) INFO:    [HyperPlay]:        Downloaded: 310.78 MB / 591.24 MB  @45.74 MB/s (52.57%)
(17:08:49) INFO:    [HyperPlay]:        Downloaded: 380.94 MB / 591.24 MB  @49 MB/s (64.43%)
(17:08:49) INFO:    [Backend]:          

HyperPlay Version: 0.3.0
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6
OS: Microsoft Windows 10 Home KERNEL: 10.0.19044 ARCH: x64
CPU: Intel Xeon® E5-2667 v3 @3.2 
RAM: Total: 11.98 GiB Available: 7.89 GiB
GRAPHICS: GPU0: Quadro P5000 VRAM: 16384MB DRIVER: 531.29 


(17:08:50) INFO:    [HyperPlay]:        Downloaded: 453.3 MB / 591.24 MB  @59.11 MB/s (76.67%)
(17:08:51) INFO:    [HyperPlay]:        Downloaded: 516.58 MB / 591.24 MB  @51.37 MB/s (87.37%)
(17:08:52) INFO:    [HyperPlay]:        Downloaded: 580.22 MB / 591.24 MB  @70.24 MB/s (98.14%)
(17:08:55) INFO:    [DownloadManager]:  Downloader: Finished downloading https://gateway.valist.io/ipfs/bafybeighwdyicwuobywg35wspky7tzmlorokccxll7nxzvy3mkreib7534/windows_amd64/hyperplay_442.zip
(17:08:55) INFO:    [DownloadManager]:  Downloader: Finished downloading https://gateway.valist.io/ipfs/bafybeighwdyicwuobywg35wspky7tzmlorokccxll7nxzvy3mkreib7534/windows_amd64/hyperplay_442.zip
(17:08:55) INFO:    [Backend]:          Deleting abort controller for 63f69d82069b92b74c8c36e9
(17:08:55) INFO:    [HyperPlay]:        Extracting C:\Users\Shadow\AppData\Roaming\hyperplay\.temp\63f69d82069b92b74c8c36e9\hyperplay_442.zip to C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros
(17:09:47) WARNING: [HyperPlay]:        Tried to install distributables from C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\dist but folder does not exist!
(17:09:47) INFO:    [DownloadManager]:  63f69d82069b92b74c8c36e9 added to download manager finished.
(17:09:47) INFO:    [DownloadManager]:  63f69d82069b92b74c8c36e9 removed from download manager.
(17:09:47) INFO:    [Frontend]:         Refreshing Library
(17:09:48) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager
(17:09:48) INFO:    [Gog]:              Found 0 game(s) to update
(17:10:15) INFO:    [Backend]:          Launching Altiros (63f69d82069b92b74c8c36e9)
(17:10:15) INFO:    [Backend]:          Preventing display from sleep
(17:10:15) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe 
(17:10:15) INFO:    [Backend]:          Creating abort controller for 63f69d82069b92b74c8c36e9
(17:10:15) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe"
(17:10:15) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\63f69d82069b92b74c8c36e9-lastPlay.log"
(17:10:15) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:10:15) INFO:    [Frontend]:         Refreshing Library
(17:10:16) INFO:    [Backend]:          operation interrupted
(17:10:45) INFO:    [Backend]:          Launching Altiros (63f69d82069b92b74c8c36e9)
(17:10:45) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe 
(17:10:45) INFO:    [Backend]:          Creating abort controller for 63f69d82069b92b74c8c36e9
(17:10:45) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe"
(17:10:45) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\63f69d82069b92b74c8c36e9-lastPlay.log"
(17:10:45) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:10:45) INFO:    [Frontend]:         Refreshing Library
(17:10:45) INFO:    [Backend]:          operation interrupted
(17:10:47) INFO:    [Backend]:          Creating abort controller for legendary-version
(17:10:47) INFO:    [Legendary]:        Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:10:47) INFO:    [Backend]:          Creating abort controller for gogdl-version
(17:10:47) INFO:    [Gog]:              Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:10:47) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:10:47) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(17:10:48) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(17:10:48) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(17:10:48) INFO:    [Legendary]:        Abort command "C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(17:10:48) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:10:48) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(17:10:49) INFO:    [Backend]:          Deleting abort controller for legendary-version
(17:11:29) INFO:    [Backend]:          Launching Altiros (63f69d82069b92b74c8c36e9)
(17:11:29) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe 
(17:11:29) INFO:    [Backend]:          Creating abort controller for 63f69d82069b92b74c8c36e9
(17:11:29) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe"
(17:11:29) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\63f69d82069b92b74c8c36e9-lastPlay.log"
(17:11:29) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:11:30) INFO:    [Frontend]:         Refreshing Library
(17:11:30) INFO:    [Backend]:          operation interrupted
(17:11:38) INFO:    [Backend]:          Creating abort controller for legendary-version
(17:11:38) INFO:    [Legendary]:        Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:11:38) INFO:    [Backend]:          Creating abort controller for gogdl-version
(17:11:38) INFO:    [Gog]:              Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:11:38) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:11:38) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(17:11:39) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(17:11:39) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(17:11:39) INFO:    [Legendary]:        Abort command "C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(17:11:39) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:11:39) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(17:11:39) INFO:    [Backend]:          Deleting abort controller for legendary-version
(17:14:11) ERROR:   [Frontend]:         Error: Request failed with status code 404
(17:15:00) INFO:    [Backend]:          Adding shortcuts for undefined
(17:15:00) INFO:    [Backend]:          Writing config for wRFGroX5vDEHSRyLJ3we2x
(17:15:00) INFO:    [Backend]:          Changed config: winePrefix from undefined to C:\Users\Shadow\Games\HyperPlay\Prefixes/Altiros2
(17:15:00) INFO:    [Backend]:          Changed config: wineCrossoverBottle from undefined to 
(17:15:00) INFO:    [Frontend]:         Refreshing Library
(17:15:00) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:15:00) INFO:    [Legendary]:        Refreshing library...
(17:15:04) INFO:    [Backend]:          Launching Altiros2 (wRFGroX5vDEHSRyLJ3we2x)
(17:15:04) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\run-no-wrapper.cmd 
(17:15:04) INFO:    [Backend]:          Creating abort controller for wRFGroX5vDEHSRyLJ3we2x
(17:15:04) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\run-no-wrapper.cmd"
(17:15:04) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\wRFGroX5vDEHSRyLJ3we2x-lastPlay.log"
(17:15:04) INFO:    [Backend]:          Process PID for sideloaded game injected: 4492
(17:15:41) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:15:41) INFO:    [Frontend]:         Refreshing Library
(17:15:41) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:15:41) INFO:    [Backend]:          operation interrupted
(17:19:40) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Altiros2
(17:19:40) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Altiros2
(17:19:40) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Altiros2
(17:19:40) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = wRFGroX5vDEHSRyLJ3we2x
(17:19:40) WARNING: [Backend]:          getExtraInfo not implemented on Sideload Game Manager. called for appName = wRFGroX5vDEHSRyLJ3we2x
(17:19:40) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Altiros2 Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(17:19:47) INFO:    [Backend]:          finished uninstalling
(17:19:47) INFO:    [Backend]:          Preventing machine to sleep
(17:19:47) INFO:    [Frontend]:         Refreshing Library
(17:19:47) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:19:47) INFO:    [Backend]:          Desktop shortcut removed
(17:19:47) INFO:    [Backend]:          Applications shortcut removed
(17:19:47) INFO:    [Backend]:          Stopping Power Saver Blocker
(17:21:03) ERROR:   [Frontend]:         Error: Request failed with status code 404
(17:21:53) ERROR:   [Frontend]:         Error: Request failed with status code 404
(17:22:31) ERROR:   [Frontend]:         Error: Request failed with status code 404
(17:22:49) INFO:    [Backend]:          Adding shortcuts for undefined
(17:22:49) INFO:    [Backend]:          Writing config for rQRw4KaE8Qbtd3uj4ydMVL
(17:22:49) INFO:    [Backend]:          Changed config: winePrefix from undefined to C:\Users\Shadow\Games\HyperPlay\Prefixes/Altiros Temp
(17:22:49) INFO:    [Backend]:          Changed config: wineCrossoverBottle from undefined to 
(17:22:49) INFO:    [Frontend]:         Refreshing Library
(17:22:49) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:22:49) INFO:    [Legendary]:        Refreshing library...
(17:22:53) INFO:    [Backend]:          Launching Altiros Temp (rQRw4KaE8Qbtd3uj4ydMVL)
(17:22:53) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\run-no-wrapper.cmd 
(17:22:53) INFO:    [Backend]:          Creating abort controller for rQRw4KaE8Qbtd3uj4ydMVL
(17:22:53) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\run-no-wrapper.cmd"
(17:22:53) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\rQRw4KaE8Qbtd3uj4ydMVL-lastPlay.log"
(17:22:53) INFO:    [Backend]:          Process PID for sideloaded game injected: 11132
(17:23:32) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:23:32) INFO:    [Frontend]:         Refreshing Library
(17:23:32) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:23:32) INFO:    [Backend]:          operation interrupted
(17:23:35) INFO:    [Backend]:          Launching Altiros (63f69d82069b92b74c8c36e9)
(17:23:35) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe 
(17:23:35) INFO:    [Backend]:          Creating abort controller for 63f69d82069b92b74c8c36e9
(17:23:35) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe"
(17:23:35) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\63f69d82069b92b74c8c36e9-lastPlay.log"
(17:23:35) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:23:35) INFO:    [Frontend]:         Refreshing Library
(17:23:35) INFO:    [Backend]:          operation interrupted
(17:28:36) INFO:    [ProtocolHandler]:  received 'hyperplay://launch/hyperplay/63f69d82069b92b74c8c36e9'
(17:28:36) INFO:    [Backend]:          Launching Altiros (63f69d82069b92b74c8c36e9)
(17:28:36) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe 
(17:28:36) INFO:    [Backend]:          Creating abort controller for 63f69d82069b92b74c8c36e9
(17:28:36) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe"
(17:28:36) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\63f69d82069b92b74c8c36e9-lastPlay.log"
(17:28:36) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:28:36) INFO:    [Frontend]:         Refreshing Library
(17:28:36) INFO:    [Backend]:          operation interrupted
(17:28:45) INFO:    [ProtocolHandler]:  received 'hyperplay://launch/hyperplay/63f69d82069b92b74c8c36e9'
(17:28:45) INFO:    [Backend]:          Launching Altiros (63f69d82069b92b74c8c36e9)
(17:28:45) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe 
(17:28:45) INFO:    [Backend]:          Creating abort controller for 63f69d82069b92b74c8c36e9
(17:28:45) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\C:\Users\Shadow\Games\HyperPlay\Heatherglade - Altiros\elteria.exe"
(17:28:45) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\63f69d82069b92b74c8c36e9-lastPlay.log"
(17:28:45) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:28:46) INFO:    [Frontend]:         Refreshing Library
(17:28:46) INFO:    [Backend]:          operation interrupted
(17:29:42) INFO:    [ProtocolHandler]:  received 'hyperplay://launch/hyperplay/64792bc2e61cddebcb7d6328'
(17:29:42) INFO:    [Backend]:          Launching The Wake - R. Labyrinth (64792bc2e61cddebcb7d6328)
(17:29:42) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Shadow\Games\HyperPlay\The Wake - The Wake - R. Labyrinth\Ragnarok's Labyrinth\Ragnarok's Labyrinth.exe 
(17:29:42) INFO:    [Backend]:          Creating abort controller for 64792bc2e61cddebcb7d6328
(17:29:42) INFO:    [Backend]:          Backend: LD_PRELOAD= "C:\Users\Shadow\Games\HyperPlay\The Wake - The Wake - R. Labyrinth\Ragnarok's Labyrinth\C:\Users\Shadow\Games\HyperPlay\The Wake - The Wake - R. Labyrinth\Ragnarok's Labyrinth\Ragnarok's Labyrinth.exe"
(17:29:42) DEBUG:   [Backend]:          Logging to file "C:\Users\Shadow\AppData\Roaming\hyperplay\GamesConfig\64792bc2e61cddebcb7d6328-lastPlay.log"
(17:29:53) INFO:    [HyperPlay]:        Injecting pid = 11884
(17:30:01) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:30:01) INFO:    [Frontend]:         Refreshing Library
(17:30:01) INFO:    [Backend]:          operation interrupted
(17:30:14) INFO:    [Backend]:          Creating abort controller for legendary-version
(17:30:14) INFO:    [Legendary]:        Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:30:14) INFO:    [Backend]:          Creating abort controller for gogdl-version
(17:30:14) INFO:    [Gog]:              Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:30:14) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:30:14) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(17:30:15) INFO:    [Backend]:          Deleting abort controller for legendary-version
(17:30:15) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(17:30:15) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(17:30:15) INFO:    [Legendary]:        Abort command "C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(17:30:15) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:30:15) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(17:38:16) INFO:    [ProtocolHandler]:  received 'hyperplay://launch/hyperplay/646d218278762e6cb3aaae65'
(17:38:16) INFO:    [Backend]:          Launching Dark Throne (Web) (646d218278762e6cb3aaae65)
(17:38:16) INFO:    [Backend]:          Creating abort controller for 646d218278762e6cb3aaae65
(17:38:24) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(17:38:24) INFO:    [Frontend]:         Refreshing Library
(17:38:27) INFO:    [Backend]:          Creating abort controller for legendary-version
(17:38:27) INFO:    [Legendary]:        Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:38:27) INFO:    [Backend]:          Creating abort controller for gogdl-version
(17:38:27) INFO:    [Gog]:              Running command: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:38:27) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:38:27) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(17:38:28) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(17:38:28) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(17:38:28) INFO:    [Legendary]:        Abort command "C:\Users\Shadow\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(17:38:28) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:38:28) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(17:38:28) INFO:    [Backend]:          Deleting abort controller for legendary-version

```

### Steps to reproduce

1. Go to Store page
2. Install a game
3. Try to launch
4. See HP crash/relaunch
5. Navigate to Library
6. Launch the same game
7. Should launch properly

### Expected behavior

Both Store & Library pages should launch the game

### hyperplay Version

Latest Stable

### System Information

- OS [e. g. "Ubuntu"]: Windows & macOS (potentially Linux)
- hyperplay Version [e. g. 2.1.1]: 0.3.0

**Comment by flavioislima** [comment]
@awantoch is this still an issue? I cannot replicate it in the latest stable.

**Comment by awantoch** [comment]
@flavioislima looks like it's fixed! closing this
