### ISSUE TITLE
Error occurs when returning to the HP Store page after being on a Store Page

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#419]
### Describe the bug

After navigating to a games Store page and then using the HP Store side nav button to return the screen goes black and displays an error in black font.

"Application error: a client-side exception has occurred (see the browser console for more information)."

### Add logs

(12:34:17) INFO:    [Legendary]:        Refreshing library...
(12:34:17) INFO:    [Legendary]:        Refreshing Epic Games...
(12:34:22) INFO:    [Backend]:          Loading MetaMask extension
(12:34:22) INFO:    [Connection]:       Connectivity: check-online
(12:34:22) INFO:    [Connection]:       Pinging external endpoints
(12:34:22) INFO:    [Backend]:          Creating abort controller for legendary-version
(12:34:22) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(12:34:27) INFO:    [Legendary]:        Legendary location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary
(12:34:27) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(12:34:27) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(12:34:27) INFO:    [Legendary]:        Game list updated, got 351 games & DLCs
(12:34:41) WARNING: [Backend]:          Protocol already registered.
(12:34:41) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(12:34:41) INFO:    [Backend]:          MetaMask extension loaded
(12:34:41) INFO:    [WineDownloader]:   Updating wine versions info
(12:34:41) INFO:    [WineDownloader]:   Fetching upstream information...
(12:34:41) INFO:    [Connection]:       All ping requests failed:
(12:34:41) INFO:    [Connection]:       AggregateError: All promises were rejected
(12:34:41) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(12:34:41) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(12:34:41) INFO:    [Backend]:          Deleting abort controller for legendary-version
(12:34:41) INFO:    [Backend]:          Creating abort controller for gogdl-version
(12:34:41) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(12:34:42) INFO:    [Backend]:          Auto Updater found version: 0.4.0 released on 2023-07-13T04:46:54.057Z with name 0.4.0
(12:34:43) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(12:34:50) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(12:34:54) INFO:    [WineDownloader]:   wine versions updated
(12:34:54) ERROR:   [Backend]:          Could not find default wine version
(12:34:54) INFO:    [Backend]:          Loading Screen Ready
(12:34:54) INFO:    [Frontend]:         Refreshing Library
(12:34:54) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(12:34:54) INFO:    [Legendary]:        Refreshing library...
(12:34:54) INFO:    [Legendary]:        Refreshing Epic Games...
(12:34:54) INFO:    [Legendary]:        Game list updated, got 352 games & DLCs
(12:34:54) INFO:    [Backend]:          Frontend Ready
(12:34:54) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(12:34:54) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(12:34:56) INFO:    [Frontend]:         Force Update
(12:34:57) INFO:    [Connection]:       Pinging external endpoints
(12:34:57) INFO:    [Connection]:       Connectivity: online
(12:34:57) INFO:    [Connection]:       Connectivity: online
(12:34:59) INFO:    [Backend]:          Starting the Download Queue
(12:35:04) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(12:35:09) INFO:    [Backend]:          

HyperPlay Version: 0.4.0
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6
OS: Microsoft Windows 10 Education KERNEL: 10.0.19045 ARCH: x64
CPU: Intel Core™ i7-6700K @4 
RAM: Total: 15.96 GiB Available: 5.64 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 12288MB DRIVER: 531.79 

(12:36:35) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Dark Throne
(12:36:35) INFO:    [HyperPlay]:        Getting install info for Dark Throne
(12:36:35) INFO:    [HyperPlay]:        Getting install info for Dark Throne
(12:36:35) INFO:    [HyperPlay]:        Getting install info for Dark Throne
(12:36:42) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Kosium Arctic Eclipse
(12:36:42) INFO:    [HyperPlay]:        Getting install info for Kosium Arctic Eclipse
(12:36:42) INFO:    [HyperPlay]:        Getting install info for Kosium Arctic Eclipse
(12:36:42) INFO:    [HyperPlay]:        Getting install info for Kosium Arctic Eclipse
(12:36:45) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Megaweapon
(12:36:45) INFO:    [ExtraGameInfo]:    Cached ExtraGameInfo data for Megaweapon outdated.
(12:36:45) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Megaweapon
(12:36:45) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Megaweapon
(12:36:45) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Megaweapon
(12:36:45) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:36:45) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:36:45) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:36:45) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:36:45) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Megaweapon Error: Error: Request failed with status code 403
    at HltbSearch.<anonymous> (C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(12:37:05) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Kosium Arctic Eclipse
(12:37:05) INFO:    [HyperPlay]:        Getting install info for Kosium Arctic Eclipse
(12:37:05) INFO:    [HyperPlay]:        Getting install info for Kosium Arctic Eclipse
(12:37:05) INFO:    [HyperPlay]:        Getting install info for Kosium Arctic Eclipse
(12:38:23) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Megaweapon
(12:38:23) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:38:23) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:38:23) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:39:53) INFO:    [Backend]:          Creating abort controller for legendary-version
(12:39:53) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(12:39:53) INFO:    [Backend]:          Creating abort controller for gogdl-version
(12:39:53) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(12:39:53) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(12:39:53) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(12:39:54) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(12:39:54) INFO:    [Backend]:          Deleting abort controller for legendary-version
(12:39:54) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(12:39:54) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(12:39:54) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(12:39:54) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(12:39:54) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(12:39:54) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(12:39:55) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(12:39:55) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(12:39:55) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(12:39:55) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(12:40:21) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Megaweapon
(12:40:21) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:40:22) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:40:22) INFO:    [HyperPlay]:        Getting install info for Megaweapon
(12:40:28) INFO:    [Backend]:          Creating abort controller for legendary-version
(12:40:28) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(12:40:28) INFO:    [Backend]:          Creating abort controller for gogdl-version
(12:40:28) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(12:40:28) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(12:40:28) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(12:40:28) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(12:40:28) INFO:    [Backend]:          Deleting abort controller for legendary-version
(12:40:28) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(12:40:28) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(12:40:28) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(12:40:28) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(12:40:28) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(12:40:28) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(12:40:29) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(12:40:29) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(12:40:29) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(12:40:29) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d

### Steps to reproduce

1. Go to Library page
2. Select any game
3. Select the 3 dot menu icon
4. Select "Store Page"
5. Click the HP Store side nav

### Expected behavior

Store page loads as normal

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/479b9502-69a8-40ea-b9ff-775701951abf)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.4.0

**Comment by nyghtstalker** [comment]
Issue is being handled with https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues/474
