### ISSUE TITLE
Overlay will minimize BR1:Infinite when triggered

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#488]
### Describe the bug

Once the user gets to the login page for BR1:Infinite and triggers the overlay the game will become minimized. This also sometimes occurs automatically before getting to the login screen but this is more intermittent and not reliably reproducible. 

### Add logs

```
(21:50:15) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for BR1 INFINITE

(21:50:15) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for BR1 INFINITE

(21:50:15) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for BR1 INFINITE

(21:50:15) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:15) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:15) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:15) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:15) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for BR1 INFINITE Error: Error: Request failed with status code 403

    at HltbSearch.<anonymous> (C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)

    at Generator.throw (<anonymous>)

    at rejected (C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(21:50:16) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:19) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:19) INFO:    [DownloadManager]:  BR1: INFINITE  was added to the download queue.

(21:50:19) INFO:    [HyperPlay]:        Installing BR1: INFINITE to C:\Users\Joe\Games\HyperPlay...

(21:50:19) INFO:    [HyperPlay]:        Downloading zip file to C:\Users\Joe\AppData\Roaming\hyperplay\.temp\0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1\BR1.zip

(21:50:19) INFO:    [HyperPlay]:        Downloading from https://gateway.valist.io/ipfs/bafybeie4t7mlnrrffwee54qlxhuqes3edn7ss7gwdyesxzxe3hmszajkte/windows_amd64/BR1.zip?token=0r1M1s1i2M6VX6pX6pOYrKqBWKvlUX7vpIXIE8Nagy0&expires=1692828961

(21:50:19) INFO:    [Backend]:          Creating abort controller for 0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1

(21:50:20) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:20) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:23) INFO:    [HyperPlay]:        Downloaded: 48.87 MB / 164.92 MB  @19.54 MB/s (29.63%)

(21:50:23) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:23) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:25) INFO:    [HyperPlay]:        Downloaded: 122.51 MB / 164.92 MB  @29.14 MB/s (74.28%)

(21:50:26) INFO:    [HyperPlay]:        Downloaded: 164.92 MB / 164.92 MB  @31.35 MB/s (100.00%)

(21:50:27) INFO:    [DownloadManager]:  Downloader: Finished downloading https://gateway.valist.io/ipfs/bafybeie4t7mlnrrffwee54qlxhuqes3edn7ss7gwdyesxzxe3hmszajkte/windows_amd64/BR1.zip?token=0r1M1s1i2M6VX6pX6pOYrKqBWKvlUX7vpIXIE8Nagy0&expires=1692828961

(21:50:27) INFO:    [DownloadManager]:  Downloader: Finished downloading https://gateway.valist.io/ipfs/bafybeie4t7mlnrrffwee54qlxhuqes3edn7ss7gwdyesxzxe3hmszajkte/windows_amd64/BR1.zip?token=0r1M1s1i2M6VX6pX6pOYrKqBWKvlUX7vpIXIE8Nagy0&expires=1692828961

(21:50:27) INFO:    [Backend]:          Deleting abort controller for 0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1

(21:50:27) INFO:    [HyperPlay]:        Extracting C:\Users\Joe\AppData\Roaming\hyperplay\.temp\0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1\BR1.zip to C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite

(21:50:27) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:27) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:32) WARNING: [HyperPlay]:        Tried to install distributables from C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\dist but folder does not exist!

(21:50:32) INFO:    [DownloadManager]:  0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1 added to download manager finished.

(21:50:32) INFO:    [DownloadManager]:  0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1 removed from download manager.

(21:50:32) INFO:    [Frontend]:         Refreshing Library

(21:50:32) INFO:    [Backend]:          Stopping Power Saver Blocker

(21:50:32) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:32) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:32) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:32) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:32) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted

(21:50:32) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}

(21:50:32) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted

(21:50:32) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}

(21:50:32) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(21:50:33) INFO:    [Gog]:              Found 0 game(s) to update

(21:50:33) INFO:    [Backend]:          Creating abort controller for legendary-check-updates

(21:50:33) INFO:    [Legendary]:        Checking for game updates: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party

(21:50:34) INFO:    [Legendary]:        installed.json updated, refreshing library

(21:50:37) INFO:    [Backend]:          Launching BR1: INFINITE (0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1)

(21:50:37) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:37) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:37) INFO:    [Backend]:          Deleting abort controller for legendary-check-updates

(21:50:37) INFO:    [Legendary]:        Found 0 games to update

(21:50:37) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\BR1.exe 

(21:50:37) INFO:    [Backend]:          Creating abort controller for 0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1

(21:50:37) INFO:    [Backend]:          Backend: LD_PRELOAD= C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\BR1.exe

(21:50:37) DEBUG:   [Backend]:          Logging to file "C:\Users\Joe\AppData\Roaming\hyperplay\GamesConfig\0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1-lastPlay.log"

(21:50:37) INFO:    [Backend]:          overlay is shown ignoring mouse events:  {

  "overlayIsShown": false

}

(21:50:37) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:37) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:50:38) INFO:    [Frontend]:         Refreshing Library

(21:50:38) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(21:50:38) INFO:    [Gog]:              Refreshing access_token

(21:50:39) INFO:    [Legendary]:        Refreshing library...

(21:50:39) INFO:    [Legendary]:        Refreshing Epic Games...

(21:50:39) INFO:    [Legendary]:        Game list updated, got 355 games & DLCs

(21:50:39) INFO:    [Backend]:          Creating abort controller for legendary-refresh

(21:50:39) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party

(21:50:39) INFO:    [Gog]:              Token refreshed successfully

(21:50:39) INFO:    [Gog]:              Getting GOG library

(21:50:40) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted

(21:50:40) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}

(21:50:40) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted

(21:50:40) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}

(21:50:40) INFO:    [Gog]:              Number of library pages: 1

(21:50:41) INFO:    [Gog]:              Saved games data

(21:50:44) INFO:    [Backend]:          Deleting abort controller for legendary-refresh

(21:52:43) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(21:52:43) INFO:    [Frontend]:         Refreshing Library

(21:52:43) INFO:    [Backend]:          operation interrupted

(21:52:43) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:52:43) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:52:44) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted

(21:52:44) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}

(21:52:44) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted

(21:52:44) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}

(21:52:44) INFO:    [Backend]:          Launching BR1: INFINITE (0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1)

(21:52:44) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:52:44) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:52:44) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:52:44) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:52:45) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\BR1.exe 

(21:52:45) INFO:    [Backend]:          Creating abort controller for 0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1

(21:52:45) INFO:    [Backend]:          Backend: LD_PRELOAD= C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\BR1.exe

(21:52:45) DEBUG:   [Backend]:          Logging to file "C:\Users\Joe\AppData\Roaming\hyperplay\GamesConfig\0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1-lastPlay.log"

(21:52:45) INFO:    [Backend]:          overlay is shown ignoring mouse events:  {

  "overlayIsShown": false

}

(21:52:46) INFO:    [Frontend]:         Refreshing Library

(21:52:46) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(21:52:46) INFO:    [Legendary]:        Refreshing library...

(21:52:46) INFO:    [Legendary]:        Refreshing Epic Games...

(21:52:46) INFO:    [Gog]:              Getting GOG library

(21:52:46) INFO:    [Legendary]:        Game list updated, got 355 games & DLCs

(21:52:46) INFO:    [Backend]:          Creating abort controller for legendary-refresh

(21:52:46) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party

(21:52:47) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted

(21:52:47) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}

(21:52:47) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted

(21:52:47) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}

(21:52:47) INFO:    [Gog]:              Number of library pages: 1

(21:52:47) INFO:    [Gog]:              Saved games data

(21:52:49) INFO:    [Backend]:          Deleting abort controller for legendary-refresh

(21:53:12) INFO:    [Backend]:          Stopping Display Power Saver Blocker

(21:53:12) INFO:    [Frontend]:         Refreshing Library

(21:53:12) INFO:    [Backend]:          operation interrupted

(21:53:12) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:53:12) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:53:13) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted

(21:53:13) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}

(21:53:13) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted

(21:53:13) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}

(21:53:13) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:53:13) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:55:03) INFO:    [Backend]:          Launching BR1: INFINITE (0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1)

(21:55:03) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:55:03) INFO:    [HyperPlay]:        Getting install info for BR1: INFINITE

(21:55:03) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\BR1.exe 

(21:55:03) INFO:    [Backend]:          Creating abort controller for 0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1

(21:55:03) INFO:    [Backend]:          Backend: LD_PRELOAD= C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\C:\Users\Joe\Games\HyperPlay\bravoready\br1infinite\BR1.exe

(21:55:03) DEBUG:   [Backend]:          Logging to file "C:\Users\Joe\AppData\Roaming\hyperplay\GamesConfig\0x9c53f773d2e2b6e079585e0dee881b16c6cc7bd568b2620a0176f867bf2fc0c1-lastPlay.log"

(21:55:03) INFO:    [Backend]:          overlay is shown ignoring mouse events:  {

  "overlayIsShown": false

}

(21:55:04) INFO:    [Frontend]:         Refreshing Library

(21:55:04) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(21:55:04) INFO:    [Legendary]:        Refreshing library...

(21:55:04) INFO:    [Legendary]:        Refreshing Epic Games...

(21:55:04) INFO:    [Gog]:              Getting GOG library

(21:55:05) INFO:    [Legendary]:        Game list updated, got 355 games & DLCs

(21:55:05) INFO:    [Backend]:          Creating abort controller for legendary-refresh

(21:55:05) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party

(21:55:05) INFO:    [Gog]:              Number of library pages: 1

(21:55:05) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted

(21:55:05) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}

(21:55:05) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted

(21:55:05) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}

(21:55:05) INFO:    [Gog]:              Saved games data

(21:55:08) INFO:    [Backend]:          Deleting abort controller for legendary-refresh

(21:59:20) INFO:    [Gog]:              Got install info from cache for 1207658876 on windows platform

(21:59:20) INFO:    [Backend]:          Creating abort controller for legendary-version

(21:59:20) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version

(21:59:20) INFO:    [Backend]:          Creating abort controller for gogdl-version

(21:59:21) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version

(21:59:21) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(21:59:21) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info

(21:59:22) INFO:    [Backend]:          Deleting abort controller for gogdl-version

(21:59:22) INFO:    [Backend]:          Deleting abort controller for legendary-version

(21:59:22) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d

(21:59:22) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d

(21:59:22) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"

(21:59:22) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(21:59:22) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(21:59:22) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info

(21:59:24) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d

(21:59:24) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d

(21:59:24) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"

(21:59:24) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
```

### Steps to reproduce

1. Launch BR1:Infinite
2. Wait until the login screen appears
3. Trigger overlay with alt+X
4. Observe game gets minimized when the overlay is triggered

### Expected behavior

Overlay should trigger on top of the game without the game being minimized

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/1447a343-ff04-46f3-a8de-cd9cfd4c383c)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/047d7b08-b51f-49fc-8404-699a8b08500d)

### hyperplay Version

Latest Stable

### System Information

- Windows 10 and Mac
- hyperplay Version 0.5.0

**Comment by nyghtstalker** [comment]
BR1 is currently disabled so I can't confirm this. I am unsure if other games are experiencing this. Closing and can reopen later, if needed.
