### ISSUE TITLE
Overlay launched but game did not due to missing requirement

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#490]
### Describe the bug

When launching Bushi a missing requirement popup appeared in order to launch the game. Right after appearing the overlay opened even though the game did not launch.

### Add logs

```
(09:20:08) INFO:    [Frontend]:         Refreshing Library

(09:20:08) INFO:    [Backend]:          Stopping Power Saver Blocker

(09:20:08) WARNING: [HyperPlay]:        Could not find game with appId = 0x86c52c7d91314be01c78588fc286241fc3b502a9ba383b8b4e9aff8e2c515e6d in API, maybe this game was delisted

(09:20:08) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0x86c52c7d91314be01c78588fc286241fc3b502a9ba383b8b4e9aff8e2c515e6d due to Error: GameId not find in API}

(09:20:09) WARNING: [Backend]:          listUpdateableGames not implemented on Sideload Library Manager

(09:20:09) INFO:    [Gog]:              Found 0 game(s) to update

(09:20:09) INFO:    [Backend]:          Creating abort controller for legendary-check-updates

(09:20:09) INFO:    [Legendary]:        Checking for game updates: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(09:20:17) INFO:    [Backend]:          Deleting abort controller for legendary-check-updates

(09:20:17) INFO:    [Legendary]:        Found 0 games to update

(09:21:12) INFO:    [ExtraGameInfo]:    Getting ExtraGameInfo data for Bushi

(09:21:12) INFO:    [ExtraGameInfo]:    Getting PCGamingWiki data for Bushi

(09:21:12) INFO:    [ExtraGameInfo]:    Getting HowLongToBeat data for Bushi

(09:21:12) INFO:    [ExtraGameInfo]:    Getting AppleGamingWiki data for Bushi

(09:21:12) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:12) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:12) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:12) ERROR:   [ExtraGameInfo]:    Was not able to get HowLongToBeat data for Bushi Error: Error: Request failed with status code 403

    at HltbSearch.<anonymous> (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:96:27)

    at Generator.throw (<anonymous>)

    at rejected (/Applications/HyperPlay.app/Contents/Resources/app.asar/node_modules/howlongtobeat/dist/main/hltbsearch.js:5:65)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(09:21:19) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Bushi

(09:21:19) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:19) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:19) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:20) INFO:    [Backend]:          Launching Bushi (0x799b758a631f05bbd441e865d0fc6be19a7b2884656c20abe5ca322bf4ebcb00)

(09:21:20) INFO:    [Backend]:          Checking if wine version exists: Wine Crossover - 22.1.1

(09:21:20) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:20) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:21) INFO:    [Backend]:          launching non-native sideloaded: /Users/joe/Games/HyperPlay/onenet/bushi/Bushi/Bushi.exe}

(09:21:21) INFO:    [Backend]:          Checking if wine version exists: Wine Crossover - 22.1.1

(09:21:21) DEBUG:   [Backend]:          Running Wine command: /Users/joe/Games/HyperPlay/onenet/bushi/Bushi/Bushi.exe 

(09:21:21) INFO:    [Backend]:          overlay is shown ignoring mouse events:  {

  "overlayIsShown": false

}

(09:21:21) DEBUG:   [Backend]:          Logging to file "/Users/joe/Library/Application Support/hyperplay/GamesConfig/0x799b758a631f05bbd441e865d0fc6be19a7b2884656c20abe5ca322bf4ebcb00-lastPlay.log"

(09:21:24) INFO:    [Frontend]:         Refreshing Library

(09:21:24) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager

(09:21:24) INFO:    [Legendary]:        Refreshing library...

(09:21:24) INFO:    [Legendary]:        Refreshing Epic Games...

(09:21:24) INFO:    [Legendary]:        Game list updated, got 356 games & DLCs

(09:21:24) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:24) INFO:    [HyperPlay]:        Getting install info for Bushi

(09:21:24) INFO:    [Backend]:          Creating abort controller for legendary-refresh

(09:21:24) INFO:    [Legendary]:        Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary list --third-party

(09:21:25) WARNING: [HyperPlay]:        Could not find game with appId = 0x86c52c7d91314be01c78588fc286241fc3b502a9ba383b8b4e9aff8e2c515e6d in API, maybe this game was delisted

(09:21:25) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0x86c52c7d91314be01c78588fc286241fc3b502a9ba383b8b4e9aff8e2c515e6d due to Error: GameId not find in API}

(09:21:25) INFO:    [Frontend]:         Force Update

(09:21:33) INFO:    [Backend]:          Deleting abort controller for legendary-refresh

(09:30:19) INFO:    [Backend]:          Creating abort controller for legendary-version

(09:30:19) INFO:    [Legendary]:        Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/legendary --version

(09:30:19) INFO:    [Backend]:          Creating abort controller for gogdl-version

(09:30:19) INFO:    [Gog]:              Running command: /Applications/HyperPlay.app/Contents/Resources/app.asar.unpacked/build/bin/darwin/gogdl --version

(09:30:25) INFO:    [Backend]:          Deleting abort controller for gogdl-version

(09:30:26) INFO:    [Backend]:          Deleting abort controller for legendary-version
```

### Steps to reproduce

1. Make sure the requirement is missing to prompt the error message
2. Launch Bushi (or any game that will trigger this error)
3. Observe error and then overlay launching

### Expected behavior

Overlay should not launch if game does not launch

### Screenshots

<img width="1717" alt="image" src="https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/2c4c84b2-cc17-4738-9ba2-f1c2f47211af">

### hyperplay Version

Latest Stable

### System Information

- Mac
- hyperplay Version 0.5.0

**Comment by nyghtstalker** [comment]
Normal first-time launch behavior for Unreal games in Wine. Will not fix.
