### ISSUE TITLE
Selecting quick results from searching does not go to game page

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#592]
### Describe the bug

When a user selects a specific quick search result it does not take the user to take games page.

### Add logs

```(21:55:07) INFO:    [Backend]:          Deleting abort controller for gogdl-get-credentials

(21:55:07) INFO:    [Gog]:              Getting GOG library

(21:55:07) INFO:    [Backend]:          Creating abort controller for gogdl-get-credentials

(21:55:07) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json auth

(21:55:09) INFO:    [Backend]:          Deleting abort controller for gogdl-get-credentials

(21:55:09) INFO:    [Backend]:          Deleting abort controller for nile-refresh

(21:55:09) INFO:    [Gog]:              Saved games data

(21:55:10) INFO:    [Backend]:          Deleting abort controller for legendary-refresh

(22:00:43) ERROR:   [Frontend]:         Error: Failed to execute 'pushState' on 'History': #<Object> could not be cloned.

    at c (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1614:2177)

    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1623:1526

    at A (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:78784)

    at onClick (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:79311)

    at Object.Wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:9862)

    at xg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10016)

    at wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10073)

    at vq (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31506)

    at jU (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31923)

    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:36845

(22:00:50) ERROR:   [Frontend]:         Error: Failed to execute 'pushState' on 'History': #<Object> could not be cloned.

    at c (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1614:2177)

    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1623:1526

    at A (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:78784)

    at onClick (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:79311)

    at Object.Wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:9862)

    at xg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10016)

    at wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10073)

    at vq (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31506)

    at jU (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31923)

    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:36845

(22:01:04) ERROR:   [Frontend]:         Error: Failed to execute 'pushState' on 'History': #<Object> could not be cloned.

    at c (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1614:2177)

    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1623:1526

    at A (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:78784)

    at onClick (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:79311)

    at Object.Wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:9862)

    at xg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10016)

    at wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10073)

    at vq (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31506)

    at jU (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31923)

    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:36845

(22:03:28) INFO:    [Backend]:          Creating abort controller for legendary-version

(22:03:28) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version

(22:03:28) INFO:    [Backend]:          Creating abort controller for gogdl-version

(22:03:28) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json --version

(22:03:28) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(22:03:28) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info

(22:03:30) INFO:    [Backend]:          Deleting abort controller for gogdl-version

(22:03:30) INFO:    [Backend]:          Deleting abort controller for legendary-version

(22:03:30) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d

(22:03:30) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d

(22:03:30) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"

```

### Steps to reproduce

1. Go to the Library
2. Click on search icon
3. Enter "Bushi"
4. Click Bushi in search results
5. Observe user is not taken to game page

### Expected behavior

User is take to what the user selected

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/e333c83d-4210-4a30-a56a-f7ba93915130)

### System Information

- Windows 10
- hyperplay Version 0.7.1

**Comment by nyghtstalker** [comment]
No longer occurs.
