### ISSUE TITLE
Selecting any game from library search does not take user to game page

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#604]
### Describe the bug

When a user selects the search results from the library the user is not taken to the game page.

### Add logs

```(15:33:45) INFO:    [Backend]:          Creating abort controller for legendary-version
(15:33:45) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(15:33:45) INFO:    [Legendary]:        Legendary location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary
(15:33:45) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(15:33:45) INFO:    [Backend]:          Loading MetaMask extension
(15:33:45) INFO:    [Connection]:       Connectivity: check-online
(15:33:45) INFO:    [Connection]:       Pinging external endpoints
(15:33:45) INFO:    [Backend]:          Creating abort controller for legendary-version
(15:33:45) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(15:33:45) INFO:    [Legendary]:        Legendary location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary
(15:33:45) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(15:33:45) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(15:33:45) INFO:    [Nile]:             Refreshing library...
(15:33:45) INFO:    [Nile]:             Refreshing Amazon Games...
(15:33:45) INFO:    [Backend]:          Creating abort controller for nile-refresh
(15:33:45) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\nile library sync
(15:33:45) INFO:    [Nile]:             Game list updated, got 64 games
(15:33:46) INFO:    [Backend]:          Registered protocol with OS.
(15:33:46) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(15:33:46) INFO:    [Backend]:          MetaMask extension loaded
(15:33:46) INFO:    [Connection]:       Connectivity: online
(15:33:46) INFO:    [Gog]:              Checking if login is valid
(15:33:46) INFO:    [Backend]:          Creating abort controller for gogdl-get-credentials
(15:33:46) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json auth
(15:33:46) INFO:    [Backend]:          Deleting abort controller for legendary-version
(15:33:46) INFO:    [Backend]:          Deleting abort controller for legendary-version
(15:33:46) INFO:    [Backend]:          Creating abort controller for gogdl-version
(15:33:46) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json --version
(15:33:46) INFO:    [Backend]:          Creating abort controller for gogdl-version
(15:33:46) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json --version
(15:33:46) INFO:    [Backend]:          Deleting abort controller for gogdl-get-credentials
(15:33:46) WARNING: [HyperPlay]:        Could not find game with appId = 0x09d1f46c7f879aa11b8f5d161bd9cdbd033b4a828b6a86f813ad15905001805f in API, maybe this game was delisted
(15:33:46) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0x09d1f46c7f879aa11b8f5d161bd9cdbd033b4a828b6a86f813ad15905001805f due to Error: GameId not find in API}
(15:33:47) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(15:33:47) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(15:33:47) INFO:    [Backend]:          Creating abort controller for nile-version
(15:33:47) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\nile --version
(15:33:47) INFO:    [Backend]:          Creating abort controller for nile-version
(15:33:47) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\nile --version
(15:33:47) INFO:    [Backend]:          Auto Updater found version: 0.8.0 released on Mon Oct 16 2023 20:30:04 GMT-0700 (Pacific Daylight Time) with name 0.8.0
(15:33:47) INFO:    [Gog]:              Saved username to config file
(15:33:47) INFO:    [Backend]:          Loading Screen Ready
(15:33:47) INFO:    [Backend]:          Deleting abort controller for nile-refresh
(15:33:47) INFO:    [Backend]:          Deleting abort controller for nile-version
(15:33:47) INFO:    [Backend]:          Deleting abort controller for nile-version
(15:33:48) INFO:    [Nile]:             Saved user data to config file
(15:33:48) INFO:    [Nile]:             Saved user data to config file
(15:33:48) INFO:    [Frontend]:         Refreshing undefined Library
(15:33:48) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(15:33:48) INFO:    [Backend]:          Creating abort controller for gogdl-get-credentials
(15:33:48) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json auth
(15:33:48) INFO:    [Legendary]:        Refreshing library...
(15:33:48) INFO:    [Legendary]:        Refreshing Epic Games...
(15:33:48) INFO:    [Nile]:             Refreshing library...
(15:33:48) INFO:    [Nile]:             Refreshing Amazon Games...
(15:33:48) INFO:    [Backend]:          Creating abort controller for nile-refresh
(15:33:48) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\nile library sync
(15:33:48) INFO:    [Nile]:             Game list updated, got 64 games
(15:33:48) INFO:    [Legendary]:        Game list updated, got 377 games & DLCs
(15:33:48) INFO:    [WineDownloader]:   Updating wine versions info
(15:33:48) INFO:    [WineDownloader]:   Fetching upstream information...
(15:33:48) INFO:    [Backend]:          Frontend Ready
(15:33:48) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(15:33:48) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(15:33:49) WARNING: [HyperPlay]:        Could not find game with appId = 0x09d1f46c7f879aa11b8f5d161bd9cdbd033b4a828b6a86f813ad15905001805f in API, maybe this game was delisted
(15:33:49) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0x09d1f46c7f879aa11b8f5d161bd9cdbd033b4a828b6a86f813ad15905001805f due to Error: GameId not find in API}
(15:33:49) INFO:    [Backend]:          Deleting abort controller for gogdl-get-credentials
(15:33:49) INFO:    [Gog]:              Getting GOG library
(15:33:49) INFO:    [Backend]:          Creating abort controller for gogdl-get-credentials
(15:33:49) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json auth
(15:33:51) INFO:    [Backend]:          Deleting abort controller for gogdl-get-credentials
(15:33:51) INFO:    [Backend]:          Deleting abort controller for nile-refresh
(15:33:51) INFO:    [WineDownloader]:   wine versions updated
(15:33:51) ERROR:   [Backend]:          Could not find default wine version
(15:33:51) INFO:    [Gog]:              Saved games data
(15:33:53) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(15:33:53) INFO:    [Backend]:          Starting the Download Queue
(15:33:58) INFO:    [Backend]:          

HyperPlay Version: 0.8.0
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

OS: Microsoft Windows 10 Education KERNEL: 10.0.19045 ARCH: x64
CPU: Intel Core™ i7-6700K @4 
RAM: Total: 63.96 GiB Available: 39.52 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 12288MB DRIVER: 545.84 


(15:33:59) INFO:    [Backend]:          

HyperPlay Version: 0.8.0
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.7.3
Nile Version: 1.0.0 Jonathan Joestar

OS: Microsoft Windows 10 Education KERNEL: 10.0.19045 ARCH: x64
CPU: Intel Core™ i7-6700K @4 
RAM: Total: 63.96 GiB Available: 39.53 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 12288MB DRIVER: 545.84 


(15:34:02) ERROR:   [Frontend]:         Error: Failed to execute 'pushState' on 'History': #<Object> could not be cloned.
    at c (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1614:2177)
    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1623:1526
    at A (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:78784)
    at onClick (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:1624:79311)
    at Object.Wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:9862)
    at xg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10016)
    at wg (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:10073)
    at vq (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31506)
    at jU (file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:31923)
    at file:///C:/Users/Joe/AppData/Local/Programs/hyperplay/resources/app.asar/build/assets/index.20909062.js:30:36845
(15:34:08) INFO:    [HyperPlay]:        Getting install info for Paradise Tycoon
(15:34:09) INFO:    [Backend]:          Creating abort controller for legendary-version
(15:34:09) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(15:34:09) INFO:    [Backend]:          Creating abort controller for gogdl-version
(15:34:09) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json --version
(15:34:09) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(15:34:09) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(15:34:09) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(15:34:09) INFO:    [Backend]:          Deleting abort controller for legendary-version
(15:34:09) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(15:34:09) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(15:34:09) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(15:34:37) INFO:    [Backend]:          Creating abort controller for legendary-version
(15:34:37) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(15:34:37) INFO:    [Backend]:          Creating abort controller for gogdl-version
(15:34:37) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json --version
(15:34:37) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(15:34:37) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(15:34:37) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(15:34:37) INFO:    [Backend]:          Deleting abort controller for legendary-version
(15:34:37) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(15:34:37) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(15:34:37) INFO:    [Legendary]:        Abort command "XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
```

### Steps to reproduce

1. Go to the library
2. Search any title
3. Click the search results
5. Observe user is not taken to game page

### Expected behavior

The user is taken to the game page of what was selected

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/49823302-81bb-43c3-9074-00333431e81f)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.8.0

**Comment by nyghtstalker** [comment]
This is now working. Closing ticket.
