### ISSUE TITLE
Overlay buttons do not work on Main

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#878]
### Describe the bug

When a user is running the client in dev mode on Main the overlay buttons (Exit Game and Back to game) are inaccessible. 

**This needs to get fixed before our next release so it does not go live**

**_NOTE: Please capitalize the "G" in in the "Back to game" button_**

### Add logs

```
(11:20:43) INFO:    [HyperPlay]:        Proxy server is ready at http://localhost:9680
(11:20:43) INFO:    [Legendary]:        Legendary location: C:\A_Repo\hyperplay-desktop-client\public\bin\win32\legendary
(11:20:43) INFO:    [Gog]:              GOGDL location: C:\A_Repo\hyperplay-desktop-client\public\bin\win32\gogdl
(11:20:43) INFO:    [Backend]:          Loading MetaMask extension
(11:20:43) INFO:    [Connection]:       Connectivity: check-online
(11:20:43) INFO:    [Connection]:       Pinging external endpoints
(11:20:43) INFO:    [Legendary]:        Legendary location: C:\A_Repo\hyperplay-desktop-client\public\bin\win32\legendary
(11:20:43) INFO:    [Gog]:              GOGDL location: C:\A_Repo\hyperplay-desktop-client\public\bin\win32\gogdl
(11:20:43) INFO:    [Gog]:              GOGDL location: C:\A_Repo\hyperplay-desktop-client\public\bin\win32\gogdl
(11:20:43) INFO:    [Nile]:             Refreshing library...
(11:20:43) INFO:    [Nile]:             Refreshing Amazon Games...
(11:20:43) INFO:    [Backend]:          Creating abort controller for nile-refresh
(11:20:43) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile library sync
(11:20:44) INFO:    [Nile]:             Game list updated, got 74 games
(11:20:44) INFO:    [Backend]:          MetaMask extension loaded
(11:20:44) INFO:    [Legendary]:        installed.json updated, refreshing library
(11:20:45) INFO:    [Backend]:          Registered protocol with OS.
(11:20:45) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(11:20:45) INFO:    [Backend]:          LaunchDarkly client initialized
(11:20:45) INFO:    [Connection]:       Connectivity: online
(11:20:45) INFO:    [Backend]:          User Not Found, removing it from Store
(11:20:45) ERROR:   [Gog]:              Unable to syncQueued playtime, userData not present
(11:20:46) WARNING: [HyperPlay]:        Could not find game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 in API, maybe this game was delisted
(11:20:46) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 due to Error: GameId not find in API}
(11:20:47) INFO:    [Backend]:          Deleting abort controller for nile-refresh
(11:20:47) ERROR:   [Backend]:          Failed to fetch system information TypeError: pciIdsFile.split is not a function or its return value is not iterable
    at getPicIds (C:\A_Repo\hyperplay-desktop-client\build\main\main.js:13815:33)
    at async populateDeviceAndVendorName (C:\A_Repo\hyperplay-desktop-client\build\main\main.js:13853:18)
    at async getSystemInfo (C:\A_Repo\hyperplay-desktop-client\build\main\main.js:13973:16)
(11:20:53) INFO:    [Nile]:             Saved user data to config file
(11:20:53) INFO:    [Backend]:          Loading Screen Ready
(11:20:53) INFO:    [Nile]:             Saved user data to config file
(11:20:53) INFO:    [Nile]:             Saved user data to config file
(11:20:53) INFO:    [Frontend]:         Refreshing undefined Library
(11:20:53) INFO:    [Legendary]:        Refreshing library...
(11:20:53) INFO:    [Nile]:             Refreshing library...
(11:20:53) INFO:    [Nile]:             Refreshing Amazon Games...
(11:20:53) INFO:    [Backend]:          Creating abort controller for nile-refresh
(11:20:53) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile library sync
(11:20:53) INFO:    [Nile]:             Game list updated, got 74 games
(11:20:53) INFO:    [Backend]:          Frontend Ready
(11:20:53) INFO:    [Nile]:             Saved user data to config file
(11:20:54) WARNING: [HyperPlay]:        Could not find game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 in API, maybe this game was delisted
(11:20:54) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 due to Error: GameId not find in API}
(11:20:54) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(11:20:54) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(11:20:54) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(11:20:54) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(11:20:54) INFO:    [Gog]:              Found 0 game(s) to update
(11:20:54) INFO:    [Nile]:             Looking for updates...
(11:20:54) INFO:    [Backend]:          Creating abort controller for nile-list-updates
(11:20:54) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile list-updates --json
(11:20:56) INFO:    [Backend]:          Deleting abort controller for nile-list-updates
(11:20:56) INFO:    [Backend]:          Deleting abort controller for nile-refresh
(11:20:58) INFO:    [Backend]:          Starting the Download Queue
(11:20:58) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(11:20:58) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(11:20:58) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(11:20:58) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(11:20:58) INFO:    [Gog]:              Found 0 game(s) to update
(11:20:58) INFO:    [Nile]:             Looking for updates...
(11:20:58) INFO:    [Backend]:          Creating abort controller for nile-list-updates
(11:20:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile list-updates --json
(11:20:58) INFO:    [Gog]:              Found 0 game(s) to update
(11:20:58) INFO:    [Nile]:             Looking for updates...
(11:20:58) INFO:    [Backend]:          Creating abort controller for nile-list-updates
(11:20:58) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile list-updates --json
(11:21:00) INFO:    [Backend]:          Deleting abort controller for nile-list-updates
(11:21:00) INFO:    [Backend]:          Deleting abort controller for nile-list-updates
(11:21:16) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for MEGAWEAPON
(11:21:16) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:16) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for MEGAWEAPON
(11:21:16) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:16) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:17) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:17) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:17) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:17) INFO:    [Backend]:          Launching MEGAWEAPON (0xcba331121eaa4ed6d6825cb64aeba3c52b083e66724aa5eae42ad039724ae964)
(11:21:17) INFO:    [Backend]:          Completing HyperPlay Quest
(11:21:17) INFO:    [Backend]:          Preventing display from sleep
(11:21:17) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:17) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:18) ERROR:   [Backend]:          Failed to complete summon task: Unauthorized
(11:21:19) ERROR:   [Backend]:          Failed to fetch system information TypeError: pciIdsFile.split is not a function or its return value is not iterable
    at getPicIds (C:\A_Repo\hyperplay-desktop-client\build\main\main.js:13815:33)
    at async populateDeviceAndVendorName (C:\A_Repo\hyperplay-desktop-client\build\main\main.js:13853:18)
    at async getSystemInfo (C:\A_Repo\hyperplay-desktop-client\build\main\main.js:13973:16)
    at async C:\A_Repo\hyperplay-desktop-client\build\main\main.js:18946:24
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:77960)
(11:21:20) INFO:    [Backend]:          launching native HyperPlay Game: J:\Users\Joe\Games\HyperPlay\benevolentmegacorp\megaweapon\megaweaponclient.exe 
(11:21:20) INFO:    [Backend]:          Creating abort controller for 0xcba331121eaa4ed6d6825cb64aeba3c52b083e66724aa5eae42ad039724ae964
(11:21:20) INFO:    [Backend]:          Backend: LD_PRELOAD= J:\Users\Joe\Games\HyperPlay\benevolentmegacorp\megaweapon\J:\Users\Joe\Games\HyperPlay\benevolentmegacorp\megaweapon\megaweaponclient.exe
(11:21:20) DEBUG:   [Backend]:          Logging to file "C:\Users\Joe\AppData\Roaming\hyperplay\GamesConfig\0xcba331121eaa4ed6d6825cb64aeba3c52b083e66724aa5eae42ad039724ae964-lastPlay.log"
(11:21:29) INFO:    [Nile]:             Saved user data to config file
(11:21:29) INFO:    [Nile]:             Saved user data to config file
(11:21:29) INFO:    [Nile]:             Saved user data to config file
(11:21:29) INFO:    [Frontend]:         Refreshing undefined Library
(11:21:29) INFO:    [Legendary]:        Refreshing library...
(11:21:29) INFO:    [Nile]:             Refreshing library...
(11:21:29) INFO:    [Nile]:             Refreshing Amazon Games...
(11:21:29) INFO:    [Backend]:          Creating abort controller for nile-refresh
(11:21:29) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile library sync
(11:21:29) INFO:    [Nile]:             Game list updated, got 74 games
(11:21:29) INFO:    [Nile]:             Saved user data to config file
(11:21:29) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(11:21:29) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(11:21:29) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(11:21:29) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(11:21:29) INFO:    [Gog]:              Found 0 game(s) to update
(11:21:29) INFO:    [Nile]:             Looking for updates...
(11:21:29) INFO:    [Backend]:          Creating abort controller for nile-list-updates
(11:21:29) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile list-updates --json
(11:21:29) INFO:    [Gog]:              Found 0 game(s) to update
(11:21:29) INFO:    [Nile]:             Looking for updates...
(11:21:29) INFO:    [Backend]:          Creating abort controller for nile-list-updates
(11:21:29) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile list-updates --json
(11:21:29) WARNING: [HyperPlay]:        Could not find game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 in API, maybe this game was delisted
(11:21:29) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 due to Error: GameId not find in API}
(11:21:30) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:30) INFO:    [HyperPlay]:        Checking for updateable games in HyperPlay Library
(11:21:30) INFO:    [HyperPlay]:        Found 0 updateable games in HyperPlay Library
(11:21:30) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:30) INFO:    [Gog]:              Found 0 game(s) to update
(11:21:30) INFO:    [Nile]:             Looking for updates...
(11:21:30) INFO:    [Backend]:          Creating abort controller for nile-list-updates
(11:21:30) INFO:    [Nile]:             Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\nile_config C:\A_Repo\hyperplay-desktop-client\public\bin\win32\nile list-updates --json
(11:21:30) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:30) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:30) INFO:    [Backend]:          Deleting abort controller for nile-list-updates
(11:21:30) INFO:    [Backend]:          Deleting abort controller for nile-list-updates
(11:21:30) INFO:    [Backend]:          Deleting abort controller for nile-list-updates
(11:21:31) INFO:    [Backend]:          Deleting abort controller for nile-refresh
(11:21:49) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(11:21:49) INFO:    [Frontend]:         Refreshing hyperplay Library
(11:21:50) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:50) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:50) WARNING: [HyperPlay]:        Could not find game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 in API, maybe this game was delisted
(11:21:50) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 0xb5b77decf0bbeb40a2b9c5c85efc9e4dd72985fc9080733857bd7c2afc702f43 due to Error: GameId not find in API}
(11:21:50) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:50) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:50) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:50) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:50) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:21:51) INFO:    [HyperPlay]:        Getting install info for MEGAWEAPON
(11:24:17) INFO:    [Backend]:          Creating abort controller for legendary-version
(11:24:17) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\A_Repo\hyperplay-desktop-client\public\bin\win32\legendary --version
(11:24:20) INFO:    [Backend]:          Creating abort controller for gogdl-version
(11:24:20) INFO:    [Gog]:              Running command: C:\A_Repo\hyperplay-desktop-client\public\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json --version
(11:24:21) INFO:    [Backend]:          Deleting abort controller for legendary-version
(11:24:21) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:24:21) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\A_Repo\hyperplay-desktop-client\public\bin\win32\legendary eos-overlay info
(11:24:21) INFO:    [Backend]:          Creating abort controller for legendary-version
(11:24:21) INFO:    [Legendary]:        Running command: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\A_Repo\hyperplay-desktop-client\public\bin\win32\legendary --version
(11:24:21) INFO:    [Backend]:          Creating abort controller for gogdl-version
(11:24:21) INFO:    [Gog]:              Running command: C:\A_Repo\hyperplay-desktop-client\public\bin\win32\gogdl --auth-config-path C:\Users\Joe\AppData\Roaming\hyperplay\gog_store\auth.json --version
(11:24:21) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:24:21) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: XDG_CONFIG_HOME=C:\Users\Joe\AppData\Roaming\hyperplay\legendaryConfig C:\A_Repo\hyperplay-desktop-client\public\bin\win32\legendary eos-overlay info
(11:24:23) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(11:24:23) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(11:24:23) INFO:    [Backend]:          Deleting abort controller for legendary-version
(11:24:23) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(11:24:23) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(11:24:23) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:24:23) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
```

### Steps to reproduce

1. Launch client in dev mode from Main branch
2. Launch any game
3. Open the overlay
4. Observe that "Exit Game" and "Back to game" buttons are inaccessible

### Expected behavior

The buttons should be accessible and work as intended

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/78f37bda-b3b8-4831-88e4-2c9be06563ca)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/ad98e65f-aefc-4805-97b7-2055c97186b4)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version: Main branch in dev mode

**Comment by nyghtstalker** [comment]
This is no longer occurring.
